DROP TABLE IF EXISTS "matches";
CREATE TABLE "matches" ("id" INTEGER PRIMARY KEY  NOT NULL , "dateofmatch" DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP);
INSERT INTO "matches" VALUES(1,'2017-08-16 20:39:04');
DROP TABLE IF EXISTS "throws";
CREATE TABLE throws (id INTEGER PRIMARY KEY  NOT NULL , matchid INTEGER NOT NULL , userid INTEGER NOT NULL , score INTEGER NOT NULL, FOREIGN KEY(matchid) REFERENCES matches(id), FOREIGN KEY(userid) REFERENCES users(id));
DROP TABLE IF EXISTS "users";
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY  NOT NULL , "name" VARCHAR NOT NULL , "wins" INTEGER DEFAULT 0, "loses" INTEGER DEFAULT 0, "average" FLOAT DEFAULT 0.0);
INSERT INTO "users" VALUES(1,'Andris',0,0,0);
INSERT INTO "users" VALUES(2,'Csabi',0,0,0);
